using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Soenneker.Quark.Gen.Themes
{
    [Generator]
    public sealed class QuarkThemeCssGenerator : IIncrementalGenerator
    {
        private const string _suiteAttributeName = "Soenneker.Quark.GenerateQuarkThemeCssAttribute";
        private const string _generatorAttributeName = "Soenneker.Quark.Gen.Themes.GenerateQuarkThemeCssAttribute";
        private const string _generatorAttributeSource =
            "// <auto-generated />\n" +
            "namespace Soenneker.Quark.Gen.Themes\n" +
            "{\n" +
            "    [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false)]\n" +
            "    public sealed class GenerateQuarkThemeCssAttribute : global::System.Attribute\n" +
            "    {\n" +
            "        public GenerateQuarkThemeCssAttribute(string outputFilePath)\n" +
            "        {\n" +
            "            OutputFilePath = outputFilePath;\n" +
            "        }\n" +
            "\n" +
            "        public string OutputFilePath { get; }\n" +
            "\n" +
            "        public bool BuildUnminified { get; set; } = true;\n" +
            "\n" +
            "        public bool BuildMinified { get; set; } = true;\n" +
            "\n" +
            "        public string TailwindOutputFilePath { get; set; } = \"tailwind/quark-theme.generated.css\";\n" +
            "\n" +
            "        public bool BuildTailwind { get; set; } = true;\n" +
            "    }\n" +
            "}\n";

        private static readonly DiagnosticDescriptor _missingOutputPath = new(
            "QTG001",
            "Missing output file path",
            "GenerateQuarkThemeCssAttribute on '{0}' requires a non-empty output file path",
            "QuarkThemeGenerator",
            DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        private static readonly DiagnosticDescriptor _themeFactoryMissing = new(
            "QTG002",
            "Theme factory missing",
            "GenerateQuarkThemeCssAttribute on '{0}' requires a single public static method or property returning Soenneker.Quark.Theme (optionally taking IServiceProvider)",
            "QuarkThemeGenerator",
            DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        private static readonly DiagnosticDescriptor _themeTypeMissing = new(
            "QTG004",
            "Theme type missing",
            "Unable to locate Soenneker.Quark.Theme in referenced assemblies",
            "QuarkThemeGenerator",
            DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(static spc =>
                spc.AddSource("GenerateQuarkThemeCssAttribute.g.cs", SourceText.From(_generatorAttributeSource, Encoding.UTF8)));

            IncrementalValuesProvider<Candidate> suiteThemeClasses = context.SyntaxProvider.ForAttributeWithMetadataName(
                _suiteAttributeName,
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) => GetCandidate(ctx));

            IncrementalValuesProvider<Candidate> generatorThemeClasses = context.SyntaxProvider.ForAttributeWithMetadataName(
                _generatorAttributeName,
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) => GetCandidate(ctx));

            var combined = suiteThemeClasses.Collect().Combine(generatorThemeClasses.Collect()).WithTrackingName("ThemeCandidates");

            context.RegisterSourceOutput(combined, static (spc, data) =>
            {
                ImmutableArray<Candidate> suiteCandidates = data.Left;
                ImmutableArray<Candidate> generatorCandidates = data.Right;
                if (suiteCandidates.IsDefaultOrEmpty && generatorCandidates.IsDefaultOrEmpty)
                    return;

                if (suiteCandidates.Any(static c => c.Error == CandidateError.MissingThemeType) || generatorCandidates.Any(static c => c.Error == CandidateError.MissingThemeType))
                {
                    spc.ReportDiagnostic(Diagnostic.Create(_themeTypeMissing, Location.None));
                    return;
                }

                var entries = new List<(string ThemeTypeName, string OutputPath, bool BuildUnminified, bool BuildMinified, string TailwindOutputPath, bool BuildTailwind)>(suiteCandidates.Length + generatorCandidates.Length);
                foreach (Candidate candidate in MergeCandidates(suiteCandidates, generatorCandidates))
                {
                    if (candidate.Error != CandidateError.None)
                    {
                        spc.ReportDiagnostic(Diagnostic.Create(candidate.Error == CandidateError.MissingOutputPath ? _missingOutputPath : _themeFactoryMissing,
                            candidate.Location, candidate.ClassName));
                        continue;
                    }

                    entries.Add((candidate.TypeName, candidate.OutputPath, candidate.BuildUnminified, candidate.BuildMinified,
                        candidate.TailwindOutputPath, candidate.BuildTailwind));
                }

                EmitManifest(spc, entries);
            });
        }

        private static Candidate GetCandidate(GeneratorAttributeSyntaxContext context)
        {
            var type = (INamedTypeSymbol)context.TargetSymbol;
            AttributeData attribute = context.Attributes[0];
            Compilation compilation = context.SemanticModel.Compilation;
            INamedTypeSymbol? themeType = compilation.GetTypeByMetadataName("Soenneker.Quark.Theme");
            string? path = GetOutputFilePath(attribute);
            CandidateError error = themeType is null ? CandidateError.MissingThemeType :
                string.IsNullOrWhiteSpace(path) ? CandidateError.MissingOutputPath :
                !TryGetThemeFactoryMember(type, themeType, compilation.GetTypeByMetadataName("System.IServiceProvider")) ?
                    CandidateError.MissingFactory : CandidateError.None;
            (bool unminified, bool minified) = GetBuildUnminifiedAndMinified(attribute);
            (string tailwindPath, bool tailwind) = GetTailwindOptions(attribute);
            return new Candidate(GetFullyQualifiedName(type), type.Name, path?.Trim() ?? string.Empty,
                unminified, minified, tailwindPath, tailwind, error, error == CandidateError.None ? null : type.Locations.FirstOrDefault());
        }

        private static IEnumerable<Candidate> MergeCandidates(
            ImmutableArray<Candidate> suiteCandidates,
            ImmutableArray<Candidate> generatorCandidates)
        {
            if (suiteCandidates.IsDefaultOrEmpty && generatorCandidates.IsDefaultOrEmpty)
                return Array.Empty<Candidate>();

            var seen = new HashSet<string>(StringComparer.Ordinal);
            var merged = new List<Candidate>(suiteCandidates.Length + generatorCandidates.Length);

            AddCandidates(suiteCandidates, merged, seen);
            AddCandidates(generatorCandidates, merged, seen);

            return merged;
        }

        private static void AddCandidates(
            ImmutableArray<Candidate> candidates,
            List<Candidate> merged,
            HashSet<string> seen)
        {
            if (candidates.IsDefaultOrEmpty)
                return;

            foreach (Candidate candidate in candidates)
            {
                if (seen.Add(candidate.TypeName))
                    merged.Add(candidate);
            }
        }

        private static bool TryGetThemeFactoryMember(INamedTypeSymbol classSymbol, INamedTypeSymbol themeType, INamedTypeSymbol? serviceProviderType)
        {
            var matches = 0;

            foreach (ISymbol? member in classSymbol.GetMembers())
            {
                if (member is IPropertySymbol property &&
                    property.DeclaredAccessibility == Accessibility.Public &&
                    property.IsStatic &&
                    property.GetMethod != null &&
                    SymbolEqualityComparer.Default.Equals(property.Type, themeType))
                {
                    matches++;
                    continue;
                }

                if (member is IMethodSymbol method &&
                    method.DeclaredAccessibility == Accessibility.Public &&
                    method.IsStatic &&
                    IsValidFactoryMethod(method, serviceProviderType) &&
                    SymbolEqualityComparer.Default.Equals(method.ReturnType, themeType))
                {
                    matches++;
                }
            }

            return matches == 1;
        }

        private static bool IsValidFactoryMethod(IMethodSymbol method, INamedTypeSymbol? serviceProviderType)
        {
            if (method.Parameters.Length == 0)
                return true;

            if (method.Parameters.Length != 1 || serviceProviderType is null)
                return false;

            return SymbolEqualityComparer.Default.Equals(method.Parameters[0].Type, serviceProviderType);
        }

        private static void EmitManifest(SourceProductionContext context, List<(string ThemeTypeName, string OutputPath, bool BuildUnminified, bool BuildMinified, string TailwindOutputPath, bool BuildTailwind)> entries)
        {
            // Each line: {ThemeTypeName}|{OutputPath}|{BuildUnminified}|{BuildMinified}|{TailwindOutputPath}|{BuildTailwind}
            // Keep it stable + dead simple to parse at runtime.
            var sb = new StringBuilder(256);

            for (var i = 0; i < entries.Count; i++)
            {
                (string themeTypeName, string outputPath, bool buildUnminified, bool buildMinified, string tailwindOutputPath, bool buildTailwind) = entries[i];

                if (themeTypeName.Length == 0 || outputPath.Length == 0)
                    continue;

                // Guard against accidental '|' or newlines in the path; you can make this stricter if you want.
                if (outputPath.IndexOf('|') >= 0 || outputPath.IndexOf('\n') >= 0 || outputPath.IndexOf('\r') >= 0 ||
                    tailwindOutputPath.IndexOf('|') >= 0 || tailwindOutputPath.IndexOf('\n') >= 0 || tailwindOutputPath.IndexOf('\r') >= 0)
                    continue;

                sb.Append(themeTypeName);
                sb.Append('|');
                sb.Append(outputPath);
                sb.Append('|');
                sb.Append(buildUnminified ? "1" : "0");
                sb.Append('|');
                sb.Append(buildMinified ? "1" : "0");
                sb.Append('|');
                sb.Append(tailwindOutputPath);
                sb.Append('|');
                sb.Append(buildTailwind ? "1" : "0");
                sb.Append('\n');
            }

            string data = EscapeVerbatimString(sb.ToString());

            string source =
                "// <auto-generated />\n" +
                "namespace Soenneker.Quark.Gen.Themes.Generated\n" +
                "{\n" +
                "    internal static class QuarkThemeCssManifest\n" +
                "    {\n" +
                "        /// <summary>Each line: {ThemeTypeName}|{OutputPath}|{BuildUnminified}|{BuildMinified}|{TailwindOutputPath}|{BuildTailwind}</summary>\n" +
                $"        public const string Data = @\"{data}\";\n" +
                "    }\n" +
                "}\n";

            context.AddSource("QuarkThemeCssManifest.g.cs", SourceText.From(source, Encoding.UTF8));
        }

        private static string GetFullyQualifiedName(INamedTypeSymbol classSymbol)
        {
            string display = classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            return display.Replace("global::", string.Empty);
        }

        private static string EscapeVerbatimString(string value) =>
            value.Replace("\"", "\"\"");

        private static string? GetOutputFilePath(AttributeData attributeData)
        {
            if (attributeData.ConstructorArguments.Length > 0)
                return attributeData.ConstructorArguments[0].Value as string;

            foreach (KeyValuePair<string, TypedConstant> namedArgument in attributeData.NamedArguments)
            {
                if (namedArgument.Key == "OutputFilePath" && namedArgument.Value.Value is string value)
                    return value;
            }

            return null;
        }

        private static (bool BuildUnminified, bool BuildMinified) GetBuildUnminifiedAndMinified(AttributeData attributeData)
        {
            var buildUnminified = true;
            var buildMinified = true;

            foreach (KeyValuePair<string, TypedConstant> namedArgument in attributeData.NamedArguments)
            {
                if (namedArgument.Key == "BuildUnminified" && namedArgument.Value.Value is bool u)
                    buildUnminified = u;
                else if (namedArgument.Key == "BuildMinified" && namedArgument.Value.Value is bool m)
                    buildMinified = m;
            }

            return (buildUnminified, buildMinified);
        }

        private static (string TailwindOutputPath, bool BuildTailwind) GetTailwindOptions(AttributeData attributeData)
        {
            const string defaultTailwindOutputPath = "tailwind/quark-theme.generated.css";
            string tailwindOutputPath = defaultTailwindOutputPath;
            var buildTailwind = true;

            foreach (KeyValuePair<string, TypedConstant> namedArgument in attributeData.NamedArguments)
            {
                if (namedArgument.Key == "TailwindOutputFilePath" && namedArgument.Value.Value is string value)
                    tailwindOutputPath = string.IsNullOrWhiteSpace(value) ? defaultTailwindOutputPath : value.Trim();
                else if (namedArgument.Key == "BuildTailwind" && namedArgument.Value.Value is bool b)
                    buildTailwind = b;
            }

            return (tailwindOutputPath, buildTailwind);
        }

    }
}
